@startuml
title <U> Get items by category

actor Admin
control "AdminController" as Controller
control "AdminService" as Service
entity AdminRepository as Dao
database MongoDB as DB

Admin -> Controller : /getItems/{category}
Controller -> Service : getItemsByCategory(category)
Service -> Dao : getItemsByCategory(category)
Dao -> DB: itemsByCategory(category)
DB --> DB
DB --> Dao : List<Item>
Dao --> Service
Service --> Controller
Controller --> Admin : (200 OK) List<Item>

@enduml