@startuml
title <U> Saving an item

actor Admin
control "AdminController" as Controller
control "AdminService" as Service
entity AdminRepository as Dao
database MongoDB as DB

Admin -> Controller : /saveItem
Controller -> Service : saveItem(item)
Service -> Dao
Dao -> DB : save(item)
DB --> Dao
Dao --> Service
Service --> Controller
Controller --> Admin : (200 OK) "Item added successfully!"

@enduml